/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class BatchProcessor */

#ifndef _Included_BatchProcessor
#define _Included_BatchProcessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     BatchProcessor
 * Method:    passBatchDataToCpp
 * Signature: (Ljava/util/ArrayList;)V
 */
JNIEXPORT void JNICALL Java_BatchProcessor_passBatchDataToCpp
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
